### ISSUE TITLE
Import error upon running version-upper

### ISSUE THREAD

**Issue by uipo78** [hkiang01/version_upper#16]
Got this error after running `version-upper`:
```bash
$ version-upper
Traceback (most recent call last):
  File "/home/carrierbm/.local/bin/version-upper", line 7, in <module>
    from version_upper import cli
ImportError: cannot import name 'cli'
```

### How to reproduce
1. Install `version-upper` via `pipx` or `pip`
2. Run `version-upper`

**Comment by hkiang01** [comment]
Fixed in https://github.com/hkiang01/version-upper/releases/tag/v0.2.2
