### ISSUE TITLE
Include semantic version with hash

### ISSUE THREAD

**Issue by Neil-Schneider** [hkiang01/version_upper#5]
As a developer, I would like to know the current semantic version along with the commit hash. 

i.e. `v1.2.1-#hash`.

**Comment by hkiang01** [comment]
The current semantic version is already contained within the config file and is preserved when bumping with a commit hash. Does this fit your use case?

**Comment by Neil-Schneider** [comment]
I guess I included a partial reason in #3 as a follow-up. I was trying to understand why there is the config json and another version file, when one is the source of truth. I was more thinking About down the line When I use this to label a build or something I would be missing the base version information.

**Comment by hkiang01** [comment]
Ah, the version.json included in tests is simply a sample file one would have in the repo. It's not required for `version-upper` to run. I understand how the name of that file could be misleading.

**Comment by hkiang01** [comment]
@Neil-Schneider does https://github.com/hkiang01/version-upper/releases/tag/v0.2.0 resolve your concern?
